/**
 * The hero background shared by every `PageIntro`.
 *
 * This lives in one place because two separate tags have to agree on it: the
 * `<img>` in `PageIntro` and the `<link rel="preload">` in `Layout.astro`.
 * The preload only accelerates the image if its `imagesrcset`/`imagesizes`
 * resolve to the *same* candidate the `<img>` picks — if the two drift apart
 * the browser fetches two different files and the preload becomes pure waste.
 *
 * The variants are generated by `pnpm run optimize:images`; keep `SRC_SET` in
 * step with `BG_WIDTHS` in `scripts/optimize-images.mjs`.
 */
export const HERO_IMAGE = {
  /** Fallback for browsers that ignore srcset; also the 1600w master. */
  src: "/cube27-bg.webp",
  srcSet:
    "/cube27-bg-480.webp 480w, /cube27-bg-640.webp 640w, /cube27-bg-960.webp 960w, /cube27-bg-1280.webp 1280w, /cube27-bg.webp 1600w",
  /** Above `lg` the image sits in a 7-of-12 column ≈ 690px; below, full-bleed. */
  sizes: "(min-width: 1024px) 690px, 100vw",
  width: 1600,
  height: 893,
  alt: "Cube27 core operations background",
} as const;
