import { useCallback, useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Reveal } from "@/components/ui/reveal";

/**
 * @cube27Component
 * @cube27ComponentId cube27LifeAtCube27
 * @cube27ComponentType section
 * @cube27ComponentPattern gallery
 * @cube27ComponentStatus stable
 * @cube27ComponentDescription "Life at Cube27" culture gallery: a framed image stage that crossfades through office/team photos, with prev/next controls, a slide counter, and a thin progress bar. Auto-advances on an interval, pauses on hover/focus, and — for reduced-motion users — turns auto-play off (manual controls only). Photos live in `public/images/office/opt/life-NN.webp` and are generated by `pnpm run optimize:images`. Tune with `count`, `eyebrow`, `title`, `body`, `intervalMs`.
 */
interface LifeAtCube27Props {
  eyebrow?: string;
  title?: string;
  body?: string;
  /** Number of sequentially-named photos in images/office/opt (life-01…life-NN). */
  count?: number;
  /** Auto-advance interval in milliseconds. */
  intervalMs?: number;
}

const PHOTO_COUNT = 24;

export function LifeAtCube27({
  eyebrow = "Culture",
  title = "Life at Cube27",
  body = "Festivals, milestones, and everyday moments from our Pune hub — the people and pride behind the work.",
  count = PHOTO_COUNT,
  intervalMs = 4500,
}: LifeAtCube27Props) {
  const photos = Array.from(
    { length: count },
    (_, i) => `/images/office/opt/life-${String(i + 1).padStart(2, "0")}.webp`,
  );

  const [active, setActive] = useState(0);
  const [paused, setPaused] = useState(false);

  const go = useCallback(
    (dir: number) => setActive((a) => (a + dir + count) % count),
    [count],
  );

  // Auto-advance, unless paused or the user prefers reduced motion.
  const reducedMotion = useRef(false);
  useEffect(() => {
    reducedMotion.current = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;
  }, []);

  useEffect(() => {
    if (paused || reducedMotion.current || count <= 1) return;
    const id = window.setInterval(
      () => setActive((a) => (a + 1) % count),
      intervalMs,
    );
    return () => window.clearInterval(id);
  }, [paused, count, intervalMs, active]);

  return (
    <section
      id="life"
      className="border-t border-cube27-border-primary bg-cube27-neutral-secondary/40 py-20 lg:py-28"
    >
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <Reveal className="max-w-3xl">
          <p className="typography-eyebrow text-[0.7rem] uppercase text-cube27-accent-primary">
            {eyebrow}
          </p>
          <h2 className="typography-heading mt-4 text-balance text-[clamp(1.75rem,3.2vw,2.35rem)] font-medium leading-[1.08] tracking-[-0.02em] text-cube27-text-primary">
            {title}
          </h2>
          <p className="mt-5 text-[1.02rem] leading-relaxed text-cube27-text-secondary">
            {body}
          </p>
        </Reveal>

        <Reveal delay={0.1}>
          <div
            className="group relative mt-10 overflow-hidden rounded-2xl border border-cube27-border-primary bg-cube27-background-primary shadow-[0_24px_80px_rgba(15,17,23,0.06)]"
            onMouseEnter={() => setPaused(true)}
            onMouseLeave={() => setPaused(false)}
            onFocusCapture={() => setPaused(true)}
            onBlurCapture={() => setPaused(false)}
            aria-roledescription="carousel"
            aria-label="Life at Cube27 photo gallery"
          >
            {/* Image stage */}
            <div className="relative aspect-[16/10] w-full sm:aspect-[16/9]">
              {photos.map((src, i) => (
                <img
                  key={src}
                  src={src}
                  alt={`Life at Cube27 — moment ${i + 1} of ${count}`}
                  loading={i === 0 ? "eager" : "lazy"}
                  decoding="async"
                  aria-hidden={i !== active}
                  className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-700 ease-out ${
                    i === active ? "opacity-100" : "opacity-0"
                  }`}
                />
              ))}

              {/* Gradient for control legibility */}
              <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/35 via-transparent to-transparent" />

              {/* Prev / Next */}
              <button
                type="button"
                onClick={() => go(-1)}
                aria-label="Previous photo"
                className="absolute left-3 top-1/2 -translate-y-1/2 grid size-10 place-items-center rounded-full bg-white/85 text-cube27-text-primary shadow-md backdrop-blur transition hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cube27-accent-primary sm:opacity-0 sm:group-hover:opacity-100"
              >
                <ChevronLeft className="size-5" />
              </button>
              <button
                type="button"
                onClick={() => go(1)}
                aria-label="Next photo"
                className="absolute right-3 top-1/2 -translate-y-1/2 grid size-10 place-items-center rounded-full bg-white/85 text-cube27-text-primary shadow-md backdrop-blur transition hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cube27-accent-primary sm:opacity-0 sm:group-hover:opacity-100"
              >
                <ChevronRight className="size-5" />
              </button>

              {/* Counter */}
              <span className="absolute bottom-3 right-4 font-mono text-[0.72rem] font-medium tracking-wide text-white/90">
                {String(active + 1).padStart(2, "0")} /{" "}
                {String(count).padStart(2, "0")}
              </span>
            </div>

            {/* Progress bar */}
            <div className="h-1 w-full bg-cube27-border-primary">
              <div
                className="h-full bg-cube27-accent-primary transition-[width] duration-500 ease-out"
                style={{ width: `${((active + 1) / count) * 100}%` }}
              />
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
