import { Reveal } from "@/components/ui/reveal";
import logoDimensions from "@/content/site/logo-dimensions.json";

/**
 * @cube27Component
 * @cube27ComponentId cube27PartnerMarquee
 * @cube27ComponentType section
 * @cube27ComponentPattern marquee
 * @cube27ComponentStatus stable
 * @cube27ComponentDescription Trusted-partners band: a quiet eyebrow + statement over an infinite, edge-faded logo strip. Logos are whitespace-trimmed full-color marks that sit directly on the page background (no card chrome — their baked-in white backgrounds are near-identical to the warm-white canvas) and scroll continuously; the strip pauses on hover and, for reduced-motion users, becomes a static horizontally-scrollable row. Logos live in `public/images/logos/opt/{n}.webp`. Tune with `count`, `eyebrow`, `statement`.
 */
interface PartnerMarqueeProps {
  eyebrow?: string;
  statement?: string;
  /** Number of sequentially-named logos in images/logos/opt (1.webp … N.webp). */
  count?: number;
}

const LOGO_COUNT = 36;

/** Logos visible before the track scrolls — roughly one wide viewport. */
const EAGER_LOGOS = 8;

/**
 * `{ "1": [width, height], … }` keyed by logo number, generated by
 * `pnpm run optimize:images`. JSON module imports widen the tuples to
 * `number[]`, so read positionally rather than destructuring a tuple type.
 */
const LOGO_DIMENSIONS: Record<string, number[]> = logoDimensions;

export function PartnerMarquee({
  eyebrow = "Trusted partners",
  statement = "Brands and enterprises that count on Cube27 to engineer their intelligent operations.",
  count = LOGO_COUNT,
}: PartnerMarqueeProps) {
  const logos = Array.from(
    { length: count },
    (_, i) => `/images/logos/opt/${i + 1}.webp`,
  );

  return (
    <section className="border-t border-cube27-border-primary bg-cube27-background-primary py-20 lg:py-28">
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <Reveal>
          <p className="typography-eyebrow text-[0.7rem] uppercase text-cube27-accent-primary">
            {eyebrow}
          </p>
          <p className="typography-heading mt-4 max-w-3xl text-balance text-[clamp(1.15rem,2vw,1.5rem)] font-medium leading-[1.3] tracking-[-0.01em] text-cube27-text-primary">
            {statement}
          </p>
        </Reveal>
      </div>

      <Reveal delay={0.1}>
        {/* A single animated track holds two identical copies of the logo set,
            so translateX(-50%) advances by exactly one copy → seamless loop. */}
        <div
          className="cube27-marquee group relative mt-10 overflow-hidden"
          aria-label="Partner and client logos"
        >
          <div className="cube27-marquee-track flex w-max">
            <ul className="flex shrink-0 items-center gap-12 pr-12 sm:gap-16 sm:pr-16">
              {logos.map((src, i) => (
                <LogoCard
                  key={src}
                  src={src}
                  index={i}
                  eager={i < EAGER_LOGOS}
                />
              ))}
            </ul>
            <ul
              className="cube27-marquee-dup flex shrink-0 items-center gap-12 pr-12 sm:gap-16 sm:pr-16"
              aria-hidden="true"
            >
              {logos.map((src, i) => (
                <LogoCard
                  key={`dup-${src}`}
                  src={src}
                  index={i}
                  eager={false}
                />
              ))}
            </ul>
          </div>
        </div>
      </Reveal>
    </section>
  );
}

function LogoCard({
  src,
  index,
  eager,
}: {
  src: string;
  index: number;
  eager: boolean;
}) {
  // Intrinsic size from logo-dimensions.json (generated by
  // `pnpm run optimize:images`). Setting width/height gives the browser each
  // logo's real aspect ratio up front, so a lazy image reserves its exact box
  // instead of collapsing to zero and snapping open on decode. The marks vary
  // from 0.65 to 5.61 in ratio, so a shared fixed size would distort them.
  // The CSS below still owns the rendered size — these attributes only supply
  // the ratio — so responsive sizing and the marquee animation are unchanged.
  const size = LOGO_DIMENSIONS[String(index + 1)];
  const width = size?.[0];
  const height = size?.[1];

  return (
    <li className="flex h-20 shrink-0 items-center justify-center sm:h-24">
      {/* Only the logos actually on screen before the track animates load
          eagerly. Lazy-loading the whole set previously left blank slots as
          the strip scrolled in; lazy-loading only the off-screen tail (and
          the entire aria-hidden duplicate, which is never visible until the
          loop wraps) keeps the strip full while freeing the LCP hero image
          from competing with 72 parallel requests. */}
      <img
        src={src}
        alt={`Partner ${index + 1}`}
        width={width}
        height={height}
        loading={eager ? "eager" : "lazy"}
        decoding="async"
        className="h-auto max-h-16 w-auto max-w-[160px] object-contain sm:max-h-20 sm:max-w-[210px]"
      />
    </li>
  );
}
